site_name: Local LLM NPC Agricultural University Platform
site_url: https://omchoksi108.github.io/Local-LLM-NPC-Multi-Agent-Agricultural-University-Platform
repo_url: https://github.com/OMCHOKSI108/Local-LLM-NPC-Multi-Agent-Agricultural-University-Platform
repo_name: OMCHOKSI108/Local-LLM-NPC-Multi-Agent-Agricultural-University-Platform

nav:
  - Home: index.md
  - User Guide: USER_GUIDE.md
  - License: LICENSE.md

theme:
  name: mkdocs

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true